"""
R_solverv2.0.py
A fully styled, production-ready desktop application for evaluating quadratic coefficients
and calculating real/complex roots. Built with tkinter and ttk.
"""

#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    May 13, 2026 07:36:10 AM CEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path
import math

_location = os.path.dirname(__file__)



_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x400+660+210")
        top.minsize(120, 1)
        top.maxsize(3204, 1061)
        top.resizable(1,  1)
        top.title("TG Root Solver")
        top.configure(background="#2b2c55")
        top.configure(cursor="heart")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        ########### start #######################
        ########### end #######################

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.35, rely=0.5, height=36, width=167)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#bfbdcc")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Terminal} -size 14 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''SOLVE''', command=self.rootsolver)

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.167, rely=0.045, height=36, width=374)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#2b2c55")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {System} -size 20 -weight bold")
        self.Label1.configure(foreground="#9b97b0")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Enter the coefficient of a,b,c.''')

        self.Label4 = tk.Label(self.top)
        self.Label4.place(relx=0.117, rely=0.675, height=41, width=474)
        self.Label4.configure(activebackground="#d9d9d9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#2b2c55")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Terminal} -size 14 -weight bold")
        self.Label4.configure(foreground="#1e9993")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="#000000")
        self.Label4.configure(text='''''')

        self.Label5 = tk.Label(self.top)
        self.Label5.place(relx=0.4, rely=0.875, height=31, width=124)
        self.Label5.configure(activebackground="#d9d9d9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="#000000")
        self.Label5.configure(text='''Copyright (TechGuy)''')

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.067, rely=0.2, relheight=0.238, relwidth=0.858)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#9894ad")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#000000")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.175, rely=0.263, height=40, width=24)
        self.Label2.configure(activebackground="#9894ad")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#9894ad")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Terminal} -size 24")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="#000000")
        self.Label2.configure(text='''x''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.233, rely=0.137, height=39, width=21)
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#9894ad")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Terminal} -size 14 -weight bold")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="#000000")
        self.Label3.configure(text='''2''')

        self.Label2_1_1 = tk.Label(self.Frame1)
        self.Label2_1_1.place(relx=0.466, rely=0.263, height=39, width=34)
        self.Label2_1_1.configure(activebackground="#d9d9d9")
        self.Label2_1_1.configure(activeforeground="black")
        self.Label2_1_1.configure(anchor='w')
        self.Label2_1_1.configure(background="#9894ad")
        self.Label2_1_1.configure(compound='left')
        self.Label2_1_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1_1.configure(font="-family {Terminal} -size 24")
        self.Label2_1_1.configure(foreground="#000000")
        self.Label2_1_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1_1.configure(highlightcolor="#000000")
        self.Label2_1_1.configure(text='''x''')

        self.Label2_1_1_1 = tk.Label(self.Frame1)
        self.Label2_1_1_1.place(relx=0.544, rely=0.263, height=40, width=34)
        self.Label2_1_1_1.configure(activebackground="#d9d9d9")
        self.Label2_1_1_1.configure(activeforeground="black")
        self.Label2_1_1_1.configure(anchor='w')
        self.Label2_1_1_1.configure(background="#9894ad")
        self.Label2_1_1_1.configure(compound='left')
        self.Label2_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1_1_1.configure(font="-family {Terminal} -size 24")
        self.Label2_1_1_1.configure(foreground="#000000")
        self.Label2_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1_1_1.configure(highlightcolor="#000000")
        self.Label2_1_1_1.configure(text='''+''')

        self.Label2_1_1_1_1 = tk.Label(self.Frame1)
        self.Label2_1_1_1_1.place(relx=0.757, rely=0.263, height=39, width=34)
        self.Label2_1_1_1_1.configure(activebackground="#d9d9d9")
        self.Label2_1_1_1_1.configure(activeforeground="black")
        self.Label2_1_1_1_1.configure(anchor='w')
        self.Label2_1_1_1_1.configure(background="#9894ad")
        self.Label2_1_1_1_1.configure(compound='left')
        self.Label2_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1_1_1_1.configure(font="-family {Terminal} -size 24")
        self.Label2_1_1_1_1.configure(foreground="#000000")
        self.Label2_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1_1_1_1.configure(highlightcolor="#000000")
        self.Label2_1_1_1_1.configure(text='''=''')

        self.Label2_1_1_1_1_1 = tk.Label(self.Frame1)
        self.Label2_1_1_1_1_1.place(relx=0.835, rely=0.263, height=39, width=34)
        self.Label2_1_1_1_1_1.configure(activebackground="#d9d9d9")
        self.Label2_1_1_1_1_1.configure(activeforeground="black")
        self.Label2_1_1_1_1_1.configure(anchor='w')
        self.Label2_1_1_1_1_1.configure(background="#9894ad")
        self.Label2_1_1_1_1_1.configure(compound='left')
        self.Label2_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1_1_1_1_1.configure(font="-family {Terminal} -size 24")
        self.Label2_1_1_1_1_1.configure(foreground="#000000")
        self.Label2_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1_1_1_1_1.configure(highlightcolor="#000000")
        self.Label2_1_1_1_1_1.configure(text='''0''')

        self.Label2_1 = tk.Label(self.Frame1)
        self.Label2_1.place(relx=0.272, rely=0.263, height=40, width=34)
        self.Label2_1.configure(activebackground="#d9d9d9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(anchor='w')
        self.Label2_1.configure(background="#9894ad")
        self.Label2_1.configure(compound='left')
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font="-family {Terminal} -size 24")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="#000000")
        self.Label2_1.configure(text='''+''')

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.078, rely=0.316, height=30, relwidth=0.085)
        self.Entry1.configure(background="#d9d9d9")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(exportselection="0")
        self.Entry1.configure(font="-family {Terminal} -size 12 -weight bold")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="#000000")
        self.Entry1.configure(insertbackground="#000000")
        self.Entry1.configure(justify='center')
        self.Entry1.configure(selectbackground="#d9d9d9")
        self.Entry1.configure(selectforeground="black")

        self.Entry2 = tk.Entry(self.Frame1)
        self.Entry2.place(relx=0.35, rely=0.316, height=30, relwidth=0.085)
        self.Entry2.configure(background="#d9d9d9")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(exportselection="0")
        self.Entry2.configure(font="-family {Terminal} -size 12 -weight bold")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="#000000")
        self.Entry2.configure(insertbackground="#000000")
        self.Entry2.configure(justify='center')
        self.Entry2.configure(selectbackground="#d9d9d9")
        self.Entry2.configure(selectforeground="black")

        self.Entry3 = tk.Entry(self.Frame1)
        self.Entry3.place(relx=0.641, rely=0.316, height=30, relwidth=0.085)
        self.Entry3.configure(background="#d9d9d9")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(exportselection="0")
        self.Entry3.configure(font="-family {Terminal} -size 12 -weight bold")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="#000000")
        self.Entry3.configure(insertbackground="#000000")
        self.Entry3.configure(justify='center')
        self.Entry3.configure(selectbackground="#d9d9d9")
        self.Entry3.configure(selectforeground="black")
    
    def rootsolver(self):
    
        
            try:
                a = float(self.Entry1.get())
                b = float(self.Entry2.get())
                c = float(self.Entry3.get())

                if a == 0:
                    value = -(c) / (b)
                    self.Label4.configure(text=f"Linear eqn: Value is {value:.2f}", foreground="#1e9993")
                else:
                
                    d = (b**2 - 4 * a * c)

                    if d < 0:
                        self.Label4.configure(text="Oops the root is complex", foreground="#cf3030")
                    elif d == 0:
                        x = -b / (2 * a)
                        self.Label4.configure(text=f"The single root is {x:.2f} ", foreground="#1e9993")

                    else:
                        x1 = (-b + math.sqrt(d))/(2*a)
                        x2 = (-b - math.sqrt(d))/(2*a)
                        self.Label4.configure(text=f"The roots are x1 = {x1:.2f} and x2 = {x2:.2f}", foreground="#1e9993")

            
                

            except ValueError:
                self.Label4.configure(text="User entered a non-number value!", foreground="#dd1919")







if __name__ == '__main__':
    root = tk.Tk()
    app = Toplevel1(root)
    root.mainloop()




